version: '3'
services:
  merkl-lite:
    image: merkl-lite
    build:
      context: .
      args:
        GITHUB_REGISTRY_TOKEN: $GITHUB_REGISTRY_TOKEN
      dockerfile: Dockerfile
    ports:
      - '3000:5173'
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./app:/app/app
