name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          registry-url: https://npm.pkg.github.com/
          scope: "@angleprotocol"

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Update package.json version
        run: |
          jq '.version = "${{ github.event.release.tag_name }}"' package.json > package.tmp.json
          mv package.tmp.json package.json
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
